# Prometheus configuration for Hyperledger Fabric monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Hyperledger Fabric nodes
  - job_name: 'hyperledger-fabric'
    static_configs:
      - targets: 
          - 'peer0.org1.example.com:9443'
          - 'peer0.org2.example.com:9444'
          - 'orderer.example.com:9445'
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Docker containers metrics (if cAdvisor is running)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8081']

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  # Custom monitoring service
  - job_name: 'monitoring-service'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Unified dashboard metrics
  - job_name: 'unified-dashboard'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/api/metrics'
    scrape_interval: 15s
